server {
    listen 80;
    server_name _;  # принимаем запросы на любой хост / IP

    # Лимит размера тела запроса — должен совпадать с MAX_CONTENT_BYTES в .env (10 МБ)
    client_max_body_size 10M;

    # Таймаут для долгих файлов
    proxy_read_timeout 60s;

    location / {
        proxy_pass         http://iges-parser:8000;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
